version: "3.3"

services:
  telegram_media_downloader:
    image: tangyoha/telegram_media_downloader:latest
    build: .
    ports:
      # Here is what you need to edit
      - "5000:5000"
    #environment:
    #  - http_proxy=http://192.168.101.30:10811
    #  - https_proxy=http://192.168.101.30:10811
    volumes:
      # Here is what you need to edit
      - "./downloads/:/app/downloads/"
      # Not recommend,this will cause move files back to copy files
      #- "./temp/:/app/downloads/temp"
      # Rclone
      - "$HOME/.config/rclone/:$HOME/.config/rclone/"

      # The following is what you don't need to edit
      - "./config.yaml:/app/config.yaml"
      - "./data.yaml:/app/data.yaml"
      - "./log/:/app/log/"
      - "./sessions/:/app/sessions"

    #restart: "unless-stopped"
# volumes:
#   sessions:
#   temp:
